train_batch_size: 32
val_batch_size: 32
test_batch_size: 32
predict_batch_size: 32
max_seq_len: 128
stride: 0.8
learning_rate: 0.1
accelerator: gpu
devices: 1  # TODO for cpu https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#num-processes
zero_class_weight: 0.05
max_epochs: 50
